# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "artalk"
primary_region = "hkg"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 23366
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
